# Generated by Django 5.2.16 on 2026-08-01 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('STARTUP', 'Startup'), ('COLLEGE_PROJECT', 'College Project'), ('FREELANCE', 'Freelance'), ('OPEN_SOURCE', 'Open Source'), ('PERSONAL_PROJECT', 'Personal Project')], default='PERSONAL_PROJECT', max_length=30)),
                ('budget_type', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('EQUITY', 'Equity'), ('NEGOTIABLE', 'Negotiable')], default='UNPAID', max_length=20)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_applications', to=settings.AUTH_USER_MODEL)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='marketplace.collaboration')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('collaboration', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='CollaborationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='marketplace.collaboration')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_skills', to='profiles.skill')),
            ],
            options={
                'unique_together': {('collaboration', 'skill')},
            },
        ),
    ]
