# Generated by Django 5.2.16 on 2026-08-07 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='admin_logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/admin/'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/favicon/'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_platform_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='contact_email',
            field=models.EmailField(default='support@hive.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/logo/'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='site_name',
            field=models.CharField(default='Hive', max_length=100),
        ),
    ]
