# Generated by Django 5.2.16 on 2026-08-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_live_demo_url_project_demo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20),
        ),
    ]
