# Generated by Django 5.2.16 on 2026-08-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('PROJECT_UPDATE', 'Project Update'), ('ACHIEVEMENT', 'Achievement')], default='TEXT', max_length=20),
        ),
    ]
